**

!framework/
!framework/**
!ui/
!ui/**
!core/
!core/**
!techmedia/
!techmedia/**

**/.git
**/.idea
**/node_modules
**/dist
**/*.log
**/*.tsbuildinfo
techmedia/.env
techmedia/.container/deploy.env
techmedia/.container/.env
techmedia/.container/*-test.env
