import { loadEnv } from "@codexsun/framework/env";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "staging", "production"]).default("development"),
  AUTH_MODE: z.enum(["cookie", "jwt", "hybrid"]).default("jwt"),
  PLATFORM_API_PORT: z.coerce.number().int().positive(),
  PLATFORM_API_URL: z.string().url("PLATFORM_API_URL must be a valid URL"),
  PLATFORM_WEB_PORT: z.coerce.number().int().positive().default(7060),
  PLATFORM_WEB_ORIGIN: z.string().url("PLATFORM_WEB_ORIGIN must be a valid URL"),
  PLATFORM_WEB_ORIGINS: z.string().default(""),
  PLATFORM_WEB_HEALTH_URL: z.union([z.literal(""), z.string().url()]).default(""),
  DB_HOST: z.string().default("127.0.0.1"),
  DB_PORT: z.coerce.number().int().positive(),
  DB_USER: z.string().min(1, "DB_USER is required"),
  DB_PASSWORD: z.string(),
  DB_DRIVER: z.enum(["mariadb", "mysql2"]).default("mariadb"),
  DB_MASTER_NAME: z.string().min(1, "DB_MASTER_NAME is required"),
  TECHMEDIA_DB_FRESH_ON_START: z.enum(["0", "1"]).default("0"),
  TECHMEDIA_DB_RESET_CONFIRM: z.string().default(""),
  TECHMEDIA_ALLOW_PRODUCTION_DB_RESET: z.enum(["0", "1"]).default("0"),
  TECHMEDIA_BACKUP_DIR: z.string().default("storage/backups/database"),
  TECHMEDIA_QUEUE_BACKEND: z.enum(["database", "bullmq-redis"]).default("database"),
  TECHMEDIA_QUEUE_COMPLETED_RETENTION_DAYS: z.coerce.number().int().positive().default(14),
  TECHMEDIA_QUEUE_FAILED_RETENTION_DAYS: z.coerce.number().int().positive().default(30),
  TECHMEDIA_QUEUE_WORKER_ENABLED: z.enum(["0", "1"]).default("1"),
  TECHMEDIA_QUEUE_WORKER_INTERVAL_MS: z.coerce.number().int().positive().default(5000),
  TECHMEDIA_REDIS_URL: z.string().min(1, "TECHMEDIA_REDIS_URL is required"),
  TECHMEDIA_INTEGRATION_ENCRYPTION_KEY: z.string().default(""),
  TECHMEDIA_ALLOW_LIVE_RESTORE: z.enum(["0", "1"]).default("0"),
  TECHMEDIA_LIVE_RESTORE_CONFIRM: z.string().default(""),
  TECHMEDIA_RESTORE_TEST_DB_NAME: z.string().default(""),
  TECHMEDIA_VERIFIED_BACKUP_ID: z.string().default(""),
  ENABLE_DEFAULT_TENANT_SEED: z.enum(["0", "1"]).default("0"),
  DEV_AUTO_TENANT_LOGIN: z.enum(["0", "1"]).default("0"),
  TENANT_DOMAIN_BASE: z.string().default("localhost"),
  DEFAULT_TENANT_ADMIN_EMAIL: z.string().default(""),
  DEFAULT_TENANT_ADMIN_NAME: z.string().default(""),
  DEFAULT_TENANT_ADMIN_PASSWORD: z.string().default(""),
  DEFAULT_TENANT_CORPORATE_ID: z.string().default(""),
  DEFAULT_TENANT_DB_NAME: z.string().default(""),
  DEFAULT_TENANT_DOMAIN: z.string().default("localhost"),
  DEFAULT_TENANT_NAME: z.string().default(""),
  DEFAULT_TENANT_SLUG: z.string().default(""),
  JWT_SECRET: z.string().min(1, "JWT_SECRET is required"),
  SOFTWARE_ADMIN_EMAIL: z.string().default(""),
  SOFTWARE_ADMIN_NAME: z.string().default(""),
  SOFTWARE_ADMIN_PASSWORD: z.string().default(""),
  SUPER_ADMIN_EMAIL: z.string().default(""),
  SUPER_ADMIN_NAME: z.string().default(""),
  SUPER_ADMIN_PASSWORD: z.string().default(""),
  TENANT_ADMIN_EMAIL: z.string().default(""),
  TENANT_ADMIN_NAME: z.string().default(""),
  TENANT_ADMIN_PASSWORD: z.string().default(""),
  STORAGE_PUBLIC_ROOT: z.string().default("storage/public"),
  STORAGE_ROOT: z.string().default("storage/app")
});

export const env = loadEnv(envSchema);
